### ISSUE TITLE
Cut 0.28.2 release

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/falco#1653]
## Scheduled to happen: > 2021-05-16, < 2021-06-09
This is a patch release. We can make the release happen as the features are merged.

## Release Steps
Process is described in this document: https://github.com/falcosecurity/falco/blob/master/RELEASE.md

## Release Blocking Features

- #1552
- [test-infra #398](https://github.com/falcosecurity/test-infra/pull/398)

## Action Items

- [x]  Update release documentation (#1652)
- [x] Update DBG configurations ([test-infra #398](https://github.com/falcosecurity/test-infra/pull/398))
- [x] Prebuilt drivers publish ([Jobs status](https://prow.falco.org/?repo=falcosecurity%2Ftest-infra&type=postsubmit&job=build-drivers-*))
- [x] Pre: Release notes
- [x] Pre: Milestones
- [x] Pre: Changelog update (#1661)
- [ ] Tag
- [ ] GH Release
- [x] Meeting-notes ([community #138](https://github.com/falcosecurity/community/pull/138))
- [ ] Blog ([falco-website #442](https://github.com/falcosecurity/falco-website/pull/442))
- [ ] Send email to cncf-falco-dev mailing list
- [ ] Announce in Falco slack channel

## Open Questions
/milestone 0.28.2
/assign @maxgio92 @leogr @zuc 
/kind documentation

**Comment by leogr** [comment]
Update:

The last PR for cutting 0.28.2 is ready to be reviewed :point_down:
https://github.com/falcosecurity/falco/pull/1552

TODO: Since the driver version changed, we should also update the Driver Build Grid configuration in test-infra

**Comment by maxgio92** [comment]
Thanks @leogr. Updated the checklist in [this issue](https://github.com/falcosecurity/falco/issues/1653)'s description.

**Comment by maxgio92** [comment]
I'm going to prepare DBG configurations

**Comment by zuc** [comment]
hello 👋

**Comment by maxgio92** [comment]
Hello @zuc!
As discussed @zuc would want to be the release shadow
/assign @zuc

**Comment by maxgio92** [comment]
Update:

Drivers have been built with success, not published yet ([test-infra #398](https://github.com/falcosecurity/test-infra/pull/398)).

**Comment by maxgio92** [comment]
Update:

Release blocking feature #398 gots merged

**Comment by maxgio92** [comment]
Update:
- Waiting for building drivers ([test-infra #398](https://github.com/falcosecurity/test-infra/pull/398))

**Comment by maxgio92** [comment]
Update:
- Prebuilt drivers have been [published](https://download.falco.org/?prefix=driver/13ec67ebd23417273275296813066e07cb85bc91/)

We can start the release!

**Comment by maxgio92** [comment]
Update:
- Opened PR #1661 for changelog update

**Comment by maxgio92** [comment]
Update:
- PR #1661 merged

**Comment by maxgio92** [comment]
Update:
- community meeting notes [#138](https://github.com/falcosecurity/community/pull/138) merged

**Comment by maxgio92** [comment]
Update:
- Release hold

**Comment by leogr** [comment]
We are blocked because `cpack` is wrongly including gRPC INSTALL targets into packages (note the `build-static` directory that should not be there) :point_down: 

![Screenshot from 2021-05-27 15-58-23](https://user-images.githubusercontent.com/3390997/119994758-30088e00-bfcd-11eb-9b04-353ff4985e28.png)

I'm investigating the problem.

**Comment by maxgio92** [comment]
Do you think @leogr this requires a fix on [libs](https://github.com/falcosecurity/libs) building system?

**Comment by leogr** [comment]
Patch ready: https://github.com/falcosecurity/falco/pull/1662
Testing in progress :rocket:

**Comment by leodido** [comment]
Since the Falco 0.29.0 milestone is due on June, 09th...

Would not make more sense to fix this in `falcosecurity/libs`, update the driver version, and release directly Falco 0.29.0 in 7 days?

**Comment by maxgio92** [comment]
Cannot the 0.29.0 be postponed? Just a question to have different alternatives in case.

**Comment by leodido** [comment]
So, we should postpone an official, and with a fixed cadence, Falco release only to release a hotfix release (0.28.2, patch level) that itself needs to patch the current libs and driver versions?

Doesn't sound very correct to me, but that's just my opinion :)

**Comment by leogr** [comment]
> Since the Falco 0.29.0 milestone is due on June, 09th...
> 
> Would not make more sense to fix this in `falcosecurity/libs`, update the driver version, and release directly Falco 0.29.0 in 7 days?

Both options are fine to me. 

Do we all agree in dismissing the `0.28.2` in favor of `0.29.0` (due date June 9)?

If so, we have to:
- apply the above fix to `falcosecurity/libs`
- update the driver version in Falco
- update the changelog
- fix the milestone value for each PR in this release

That's totally fine.

Please confirm!

**Comment by maxgio92** [comment]
Sorry @leodido I didn't get the point that the 0.29.0 has been actually planned, you're right in my opinion.

In that case I agree with you all to dismiss 0.28.2 in favor of 0.29.0.

**Comment by fntlnz** [comment]
Closing since we agreeed to cut 0.29.0 directly.
/close
