### ISSUE TITLE
[tracking] cleanup inactive maintainers

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/falco#2115]
### Motivation

As part of the preparations for our graduation submission, this issue tracks the process of reviewing and cleaning up the OWNERS files of each repository. This is a step for https://github.com/falcosecurity/falco/issues/2106 and follows the community call discussion of 2022-06-29.

The OWNERS files of each repository will be updated to remove maintainers that have been inactive for the past 6 months as for the criteria of our governance (see: https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md#project-inactivity).

Developer activity is reviewed from the https://devstats.cncf.io/ API (ref: https://github.com/cncf/devstatscode/blob/master/API.md, https://github.com/cncf/devstatscode/blob/master/devel/api_dev_act_cnt.sh). Inactivity means having recorded zero or very little devstats over the past 6 months (2022-01-01 - 2022-07-01).

Inactive maintainers will be moved from `approvers` to `emeritus_approvers` (see: https://www.kubernetes.dev/docs/guide/owners/#emeritus) so that they will have the possibility to step up again in the future.

If any of the maintainers involved wishes to continue with their role, or to become active again, this issue (or any of its linked PRs) is the right place of discussion.

These repositories are excluded from the rewiew:

  - **Special repositories**
    - falcosecurity/community
    - falcosecurity/evolution
    - falcosecurity/.github
    - falcosecurity/template-repository
  - **Repositories opened less than 6 months ago**
    - falcosecurity/deploy-kubernetes
    - falcosecurity/kernel-crawler
    - falcosecurity/plugin-sdk-cpp
    - falcosecurity/falco-aws-terraform
    - falcosecurity/libs-sdk-governance
  - **Repositories that had no activity (or very little) in the past 6 months**
    - falcosecurity/katacoda-scenarios
    - falcosecurity/client-py
    - falcosecurity/client-rs
    - falcosecurity/kilt
    - falcosecurity/pdig

### Repositories where inactive owners need to be updated

- [ ] falcosecurity/falco - TODO
- [ ] falcosecurity/libs - TODO
- [ ] falcosecurity/charts - TODO
- [ ] falcosecurity/falco-website - TODO
- [ ] falcosecurity/plugins - TODO
- [ ] falcosecurity/plugin-sdk-go - TODO
- [ ] falcosecurity/client-go - TODO
- [ ] falcosecurity/driverkit - TODO
- [ ] falcosecurity/event-generator - TODO
- [ ] falcosecurity/falco-exporter - TODO
- [ ] falcosecurity/falcoctl - TODO
- [ ] falcosecurity/falcosidekick - TODO
- [ ] falcosecurity/falcosidekick-ui - TODO
- [ ] falcosecurity/test-infra - TODO

**Comment by jasondellaluce** [comment]
@bencer, @developer-guy, @fntlnz, @jonahjon, @keisukeyamashita, @kris-nova, @ldegio, @leodido, @leogr, @lucperkins, @markyjackson-taulia, @mfdii, @mstemm, @nestorsalceda, @nibalizer, @radhikapc, @rajakavitha1, @sreedaum

**Comment by markyjackson-taulia** [comment]
Ack @jasondellaluce

**Comment by fntlnz** [comment]
Citing our governance:
> If they decide to step down they open a pull request to be removed from the OWNERS files.

I did not decide to step down. It’s important for me to keep being a maintainer of Falco to ensure that our community has a different voice out there  than employees of a single company. When I will see a diverse pool of maintainers I will think about stepping down. Even in that case, it’s a decision I will take based on the status of the project. I’m continuing to serve the community by making sure that the project is openly governed.

Please make sure to not remove my name from the approved files.

**Comment by leodido** [comment]
> Citing our governance:
> 
> > If they decide to step down they open a pull request to be removed from the OWNERS files.
> 
> I did not decide to step down. It’s important for me to keep being a maintainer of Falco to ensure that our community has a different voice out there than employees of a single company. When I will see a diverse pool of maintainers I will think about stepping down. Even in that case, it’s a decision I will take based on the status of the project. I’m continuing to serve the community by making sure that the project is openly governed.
> 
> Please make sure to not remove my name from the approver files.

Likewise.

**Comment by maxgio92** [comment]
IMHO there is an ambiguiti in this sentence:
> If they decide to step down they [1] open a pull request to be removed from the OWNERS files.
1. Active maintainers or inactive maintainers?

**Comment by fntlnz** [comment]
@maxgio92 no ambiguity, please read the whole thing

> Any existing maintainer that does not show significant activity on the project they maintain can be removed. Periodically, maintainers review the list of maintainers and their activity during the past six months.
In case the maintainer involvement in the past six months doesn't meet the requirements in this file they will be contacted to ask wether they want to continue being a maintainer. If they decide to step down they open a pull request to be removed from the OWNERS files.


Again, In my case I don't consider myself inactive.  I'm less active than others but it's no justification to single-handedly
remove me from a project that I know like my pockets and where I am and will be always useful - because I'm here to help.

**Comment by leodido** [comment]
> IMHO there is an ambiguity in this sentence:
> 
> > If they decide to step down they [1] open a pull request to be removed from the OWNERS files.
> 
>     1. Active maintainers or inactive maintainers?

I think there's no ambiguity at all.

> they will be contacted to ask whether they want to continue being a maintainer.

**Comment by fntlnz** [comment]
@leodido 
> they will be contacted to ask whether they want to continue being a maintainer.
No evidence of being contacted from my side as well.

**Comment by markyjackson-taulia** [comment]
I can also say other than being tagged in this, there has been no contact with me.
I was originally removed under the same circumstances previously and aired my concerns over that.
I would like to remain as well.

**Comment by maxgio92** [comment]
I agree on the fact that the contact is a requirement. I wasn't aware it has been missed.

Maybe a clarification on what is considered inactivity can help on the governance?
Also, how a maintainer should be contacted, to avoid mistakes (e.g. maintainer email?).

**Comment by leodido** [comment]
This is not the place to discuss changes to the governance (there's a process for that in the governance itself).

**Comment by markyjackson-taulia** [comment]
@maxgio92 i would use the maintainers contact email. Also, a dm via slack is good. Also the mailing list as a public artifact.
I do think it would be good to have a timeline defined via governance docs as well.

**Comment by leogr** [comment]
Thanks for raising your concerns, and sorry for any unwelcome surprise. I would like to clarify what we're doing. This message is a bit long, but I want to talk about the process for maintainer cleanup that our governance requires, and why we're doing it.

**The process**

The [Project inactivity](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md#project-inactivity) section of our [GOVERNANCE.md](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md) mentions that we should "periodically review inactive maintainers".

This issue is the review of the maintainers' activity; it does not necessarily imply removal. Since the governance does not specify how to perform the review, we took inspiration from k8s (see https://github.com/kubernetes/org/issues/2013).

We are sorry that this has taken some by surprise: we tried hard to introduce this process transparently.

The governance does not indicate how maintainers should be contacted, so I proactively sent a message to the private Falco maintainer channel on the CNCF Slack on 24th June (link [here](https://cloud-native.slack.com/archives/C022CMVDM5H/p1656053528235989) - only channel members can open the link; screenshot attached), but I received no response. Then, Jason introduced the cleanup process during the community call of 29th June. As the third line of contact, Jason tagged inactive maintainers in this PR, which acts as a place for the conversation itself.

Since maintainership is a per-repository status, I see all these PRs as an invitation to discuss in each repository, and [vote if necessary](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md#conflict-resolution-and-voting). In each repo, active maintainers will be the ones to decide with respect to the governance. The voting process is documented [here](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md#single-project-conflicts).

Retaining maintainer status is clearly linked to [maintainer duties](https://github.com/falcosecurity/.github/blob/master/GOVERNANCE.md#maintainer-responsibilities), however I hope we can keep many maintainers if they resume activity.

**Why we are doing this**


As maintainers we think Falco is in good shape and ready to try for CNCF graduation again. We spoke with a few CNCF TOC members and asked for advice. One of the main points we heard was that the listed maintainers of the project should match with the contribution as seen through devstats. This process is also something many other CNCF projects have done before, e.g., k8s, helm.

We are committed to pursuing open and inclusive governance for Falco. However, keeping inactive maintainers is not a solution for vendor diversity. Instead, we are seeing increasing participation from different vendors and adding new active maintainers, which is what we really need to address the issue.

Finally, we are grateful for all the work past maintainers have done. The _emeritus maintainer_ status is a way we can acknowledge your hard work in perpetuity.

It would be great to preserve as many active maintainers as possible, and if emeritus maintainers wish to resume activity, we will reinstate the current maintainer status.

_One final note: it's a valid point that we could improve the governance to make maintainer communications more explicit, and perhaps rethink maintainers' duties. However, that should be a separate discussion._

cc @fntlnz @leodido @nestorsalceda @markyjackson-taulia 

![Screenshot from 2022-07-08 09-33-04](https://user-images.githubusercontent.com/3390997/177941133-572f7b8f-b4a4-4508-9c25-bf138ecd0580.png)

**Comment by leogr** [comment]
Hey @jasondellaluce 

I think we should also review special repositories as I have noticed that there are maintainers in the OWNERS who have not been active for over a year (somebody has even left the organization).

Except for the [falcosecurity/template-repository](https://github.com/falcosecurity/template-repository) that I agree with @FedeDP   it should be archived, see his proposal [here](https://github.com/falcosecurity/evolution/issues/154).

WDYT?

cc @falcosecurity/maintainers @falcosecurity/evolution-maintainers @falcosecurity/community-maintainers

**Comment by jasondellaluce** [comment]
@leogr 👇🏼 

> I think we should also review special repositories as I have noticed that there are maintainers in the OWNERS who have not been active for over a year (somebody has even left the organization).

+1 on this. The reason why they were excluded from the initial review, as stated in the issue description, is that I didn't find a clear rationale on how maintainers for special repositories have been selected, and devstats numbers are not very meaningful in them. I think it makes lot of sense to start reviewing the maintainer lists of special repositories too.

I will start opening PRs for those repositories too, meant to start the discussion on each of them before taking a decision, and will update the issue accordingly.

> Except for the [falcosecurity/template-repository](https://github.com/falcosecurity/template-repository) that I agree with @FedeDP it should be archived, see his proposal https://github.com/falcosecurity/evolution/issues/154.

Strong +1 for me. The template-repository has not been used consistently in our organization, and I think it is generally bad to have a pre-defined set of default maintainers and license when creating new repos: it should be up to the repository opener to take this decision after gaining community consensus on https://github.com/falcosecurity/evolution, and I think that such pre-defined files can just become error-prone.

**Comment by kris-nova** [comment]
Please see #1942 where I believe we can migrate some of the existing approvers to a new role.

**Comment by jasondellaluce** [comment]
As @leogr suggested in some of the related PRs and issues, I agree on moving this discussion to `falcosecurity/evolution`.

Quoting the readme of the `evolution` repository: 
> This repo aims to document the evolution process of The Falco Project.

Since this issue covers many PRs across the organization, and not just the `falco` repository, I'd ask @leogr or some other maintainer of both repositories to move this issue to `falcosecurity/evolution`.

**Comment by leogr** [comment]
> Since this issue covers many PRs across the organization, and not just the `falco` repository, I'd ask @leogr or some other maintainer of both repositories to move this issue to `falcosecurity/evolution`.

Sure :+1: 

Moving it right now.
