### ISSUE TITLE
[UMBRELLA] How do you deploy Falco in production?

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#2376]
**Motivation**

_This issue is currently a WIP. It aims to collect feedback on how users deploy Falco in their environment._

By reading this [slack thread](https://kubernetes.slack.com/archives/CMWH3EH32/p1674260518054889), I've noticed that not all users prefer using our [official Falco distribution](https://falco.org/docs/getting-started/download/). Instead, some may choose to internally build Falco packages/images (for example, see [this](https://kubernetes.slack.com/archives/CMWH3EH32/p1674581910959499?thread_ts=1674260518.054889&cid=CMWH3EH32) and [this](https://kubernetes.slack.com/archives/CMWH3EH32/p1674583354188249?thread_ts=1674260518.054889&cid=CMWH3EH32)). 

As a maintainer, I'd like to know if there's any common need that we are missing. :thinking:  
So, I've created this issue as a starting point to collect user feedback. 

If you are a **Falco production user**, please answer a few questions :point_down:  and share your experience!
Your feedback is precious to us! :pray: 

```
- Do you use:
  - [ ] only officially released version?
  - [ ] customized build from source code

- How do you install Falco in production?
  - [ ] Using an official DEB/RPM/TAR.GZ package
  - [ ] Using an official docker image
  - [ ] Building Falco packages/images by yourself (if yes, explain your need)
  - [ ] Other? (explain your need)
 
- If you deploy Falco on K8s, what's your installation method?
  - [ ] Using the official Falco [Helm chart](https://github.com/falcosecurity/charts/tree/master/falco)
  - [ ] Custom manifest files based on [official examples](https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes)
  - [ ] Other? (explain your need)

- Is any Falco feature you disabled or didn't want to use in production? If yes, Why?

- Is any specific deployment need currently unmet by the official Falco distribution?

- Briefly describe your deployment scenario, if possible.
```

/kind documentation

**Additional context**

TODO

**Comment by Happy-Dude** [comment]
- Do you use:
  - [x] customized build from source code

- How do you install Falco in production?
  - [x] Building Falco packages/images by yourself (if yes, explain your need)
  * better supply-chain control from source to installation of Falco; this was part of my org's mitigation for certain risks assessed in a threat model
  * unattended install experience during deployment of package via config management tool; change made to not prompt for probe selection since we use the bpf-probe (also avoids dependencies that the probe needs), and also avoids making a network connection to see if a pre-built probe is available upstream to download (we deploy a custom kernel, and same supply-chain concerns apply to reaching for upstream probes)
  * better control of dependencies overall (use bundled deps, not depending on `dkms` while using bpf-probe)
  * creating a non-stripped build with some debug symbols (see also https://github.com/falcosecurity/falco/issues/2268)
  * applying bugfixes or features that are not in release version

- Is any Falco feature you disabled or didn't want to use in production? If yes, Why?
    * the driver selection post-install script is unnecessary when we know which probe to use beforehand and have pre-built probes internally

- Is any specific deployment need currently unmet by the official Falco distribution?
    * My org's deployment is on bare metal; a lot of Falco-related projects assume K8S/Helm distribution
    * falco-exporter, falcosidekick are not available in the an apt-repo, requiring publishing of packages internally
