### ISSUE TITLE
Cut Falco 0.34.1 release

### ISSUE THREAD

**Issue by alacuku** [falcosecurity/falco#2421]
## Type
This is a **patch** release. 

As proposed in the Feb 15th 2023 community call, I will be the release manager for this version.

## Date
Feb 20th, 2023

## Release Versions

- [x] libs `0.10.4` https://github.com/falcosecurity/libs/releases/tag/0.10.4
- [x] drivers https://github.com/falcosecurity/libs/releases/tag/4.0.0%2Bdriver (same as 0.34.0, no drivers changes are expected in this patch)
- [x] Falco `0.34.1` https://github.com/falcosecurity/falco/releases/tag/0.34.1

## Release Steps
Read the [release process](https://github.com/falcosecurity/falco/blob/master/RELEASE.md) for a detailed explanation.

## Release Blocking PRs

* #2418 
* #2412 
* #2424
* falcosecurity/libs#871
* falcosecurity/libs#888
* falcosecurity/libs#894
* falcosecurity/libs#895

## Action Items
- [x] Pre-Release
   - [x] Update milestones to 0.34.1
   - [x] Changelog
- [x] Release
   - [x] Sync release branch with upstream one: #2422 
   - [x] Bump libs version #2422 #2424
   - [x] Tag
   - [x] Github Release
   - [x] Set the release branch as protected falcosecurity/test-infra#1008
 - [x] Website
   - [x] Bump Falco version to 0.34.1 https://github.com/falcosecurity/falco-website/pull/829
   - [x] Falco 0.34.1 blogpost https://github.com/falcosecurity/falco-website/pull/828
 - [x] Community
   - [x]  archive meeting notes https://github.com/falcosecurity/community/pull/176
 - [x] Announcements 
   - [x] Falco slack channel
   - [x] Falco mailing list
 - [x] Post-Release
   - [x] Release new Helm Chart for Falco 0.34.1 falcosecurity/charts#469

## Test checklist
The following items are useful for anyone that wishes to test this release when RC's are out:
* Test SSL certificates:
   * Try to reproduce the following issue: #2274
 * [Installation types](https://falco.org/docs/getting-started/installation/)
    * Kubernetes Helm Chart
    * Container only (without kubernetes)
    * eBPF probe installation
    * Local DEB package
    * Local RPM package
    * Local binary
    * Local binary (musl-static)

/assign @alacuku 
/kind documentation

**Comment by FedeDP** [comment]
Following https://github.com/falcosecurity/falco/pull/2408, i created [release/0.34.x](https://github.com/falcosecurity/falco/tree/release/0.34.x) release branch!
