### ISSUE TITLE
[UMBRELLA] Migrate open rules PR to the new rules repository

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#2446]
**Motivation**

Since Falco 0.34, all rules live in a new repository: https://github.com/falcosecurity/rules
However, we have several open PR that still points to the main repository and need to be migrated.
 
**Feature**

For the following PRs:

```[tasklist]
- [ ] https://github.com/falcosecurity/falco/pull/2227
- [ ] https://github.com/falcosecurity/falco/pull/2202
- [ ] https://github.com/falcosecurity/falco/pull/2199
- [ ] https://github.com/falcosecurity/falco/pull/2202
```

Ask the PR author if they can port the PR to the new repo. If the author is responsive or needs support, maintainers can perform the migration.

/milestone 0.35.0
cc @falcosecurity/rules-maintainers

**Comment by FedeDP** [comment]
Can this be closed? @leogr

**Comment by leogr** [comment]
> Can this be closed? @leogr 

Sure!

/close
