### ISSUE TITLE
[TRACKING] `modern_bpf` production-readiness

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#2451]
Track `modern_bpf` production-readiness tests and checks.

- [x] System call coverage / parity w/ current eBPF probe
- [x] Resource utilization overhead guidance
- [x] Real-life production deployment stability

**Comment by incertum** [comment]
**Resource utilization overhead guidance:**

_Memory:_

The modern_bpf utilizes the new bpf [ring buffer](https://www.kernel.org/doc/html/next/bpf/ringbuf.html) and has a different memory footprint than the current bpf driver that uses the perf buffer. Falco core maintainers reached out to the [mailing list](https://lore.kernel.org/bpf/CAEf4BzbYoGY2e_Nf1EOgzDdjGOLbSjJ5OmHRDFnYUA_VDYD6zQ@mail.gmail.com/T/#t)(Thanks @Andreagit97 for being the primary point of contact!) to inquiry about the differences and their implications especially in Kubernetes environments where limits have to be carefully set to avoid OOM killer interference with the Falco daemonset deployment.

Current guidance is to find an optimal buffer size ([syscall_buf_size_preset](https://github.com/falcosecurity/falco/blob/e4d575b10d54a89c8a4ac4a4fbb7e77cb02e17bb/falco.yaml#L226)) and number of CPUs per one ring buffer ([modern_bpf.cpus_for_each_syscall_buffer](https://github.com/falcosecurity/falco/blob/e4d575b10d54a89c8a4ac4a4fbb7e77cb02e17bb/falco.yaml#L292)). The current recommendation is to keep the buffer size the lowest possible while increasing the number of CPUs per one ring buffer while ensuring no kernel side drops are observed (enable logging via [syscall_event_drops](https://github.com/falcosecurity/falco/blob/e4d575b10d54a89c8a4ac4a4fbb7e77cb02e17bb/falco.yaml#L146) config). The effect will be less overall memory pre-allocation and/or usage wrt to how the kernel would report memory ... 


_CPU_:

TBA

**Comment by incertum** [comment]
**Real-life production deployment stability:**

- Falco w/ modern_bpf has been running in a stable manner on a small number (~2K) of real-life production servers for some time
- Stable resource utilization metrics (equivalent profiles over time when compared to current bpf)
- Equivalent log quality

Tips:

See https://github.com/falcosecurity/falco/issues/2451#issuecomment-1478647315 -> experiment w/ buffer size and number of CPUs per ring buffer. 

In addition, please note that classic RSS memory metric is not reflective of what Falco is using. You will notice that RSS reflects more or less number_of_buffers * buffer_size as constant over time. 

However, Falco's memory usage grows over time because Falco caches processes in userspace, but eventually should plateau.

In Kubernetes, use `container_memory_working_set_bytes` as memory metric instead. This is also the metric the OOM killer uses. `/sys/fs/cgroup/memory/memory.usage_in_bytes as seen from your Falco daemonset container is close enough. Memory used appears to be for the most less than RSS, but p90 can go above.

CPU usage seems equivalent to the current bpf. Note that some workloads exhibit stable usage over time while other workloads can cause CPU usage to fluctuate over time. This is because Falco's CPU usage is in direct relationship with the amount of work done in the kernel which is tightly coupled with the rate of system calls Falco traces.

**Comment by Andreagit97** [comment]
Wow, thank you @incertum for this feedback :heart:! I'm super happy to hear that the modern probe is reaching the production-ready state :tada: 

> System call coverage / parity w/ current eBPF probe

For what concerns this point, I think we have done it! we miss only 64/32 versions of some syscalls (https://github.com/falcosecurity/libs/issues/723#issuecomment-1375490379), but they are never compiled on `x86/arm64/s390x` so I wouldn't consider them as strictly required right now :)

**Comment by incertum** [comment]
Multiple contributors further made `modern_bpf` even more robust. Let's close this issue and mark it as completed.
Let's attach milestone 0.35 to it.
