### ISSUE TITLE
[tracking] Falco v0.35 release

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/falco#2554]
## Scheduled to happen: ~2023-06-07

During the community call of 2023-05-17 I proposed myself as a release manager, and together with the other maintainers we plan to release v0.35 as soon as possible.

I Will keep this issue updated with the current status and progress.

## Current Status

- [x] falcosecurity/libs tracking release issue: https://github.com/falcosecurity/libs/issues/1092
- [x] Code freeze in falcosecurity/libs
- [x] Code thaw in falcosecurity/libs
- [x] Release libs [0.11.2](https://github.com/falcosecurity/libs/milestone/19)
  - [x] https://github.com/falcosecurity/libs/releases/tag/0.11.2 
- [x] Release drivers [5.0.1](https://github.com/falcosecurity/libs/milestone/17)
  - [x] https://github.com/falcosecurity/libs/releases/tag/5.0.1%2Bdriver
- [x] Code freeze in falcosecurity/falco
- [x] Open release branch in Falco
  - [x] Branch-protect the branch
- [x] Code thaw in falcosecurity/falco
- [x] Release Falco v0.35.0

## Release Steps

Process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

## Manual Testing Action Items

- [x] Running Falco on Kubernetes with the official Helm Charts
- [x] Running Falco from RPM and DEB artifacts
- [x] Running Falco in a container with the official images
- [x] Running/fuzzing Falco with multiple event sources active in parallel
- [x] Running/fuzzing Falco with variable syscall buffer dimension
- [x] Running Falco in all officially-supported architectures (x86_64, ARM64)
- [x] Running Falco with the supported drivers (kmod, eBPF, gVisor, trace files)
- [x] Test Falco with event generator
- [x] Test that plugins are correctly loaded
- [x] Test memory and CPU usage (with Valgrind and other tools)
- [x] Test latest version of driver loader
- [x] Test that k8s metadata enrichment client works as expected
- [x] Test that all Falco CLI options work as expected
- [x] Check that Falco log messages are correct and consistent
- [x] Test that Falco ruleset loading and validation works as expected

## Action Items

- [x] **Pre-Release**
  - [x]  Milestone: https://github.com/falcosecurity/falco/milestone/29
  - [x] Sync with new falcosecurity/libs release 0.11.1:
    - [x] https://github.com/falcosecurity/falco/pull/2615 
  - [x] Sync with new falcosecurity/libs driver release 5.0.1:
   -  [x] https://github.com/falcosecurity/falco/pull/2600 
  - [x] Release plugin-sdk-go
    - [x] https://github.com/falcosecurity/plugin-sdk-go/releases/tag/v0.7.1
  - [x] Release falcoctl
    - [x] https://github.com/falcosecurity/falcoctl/releases/tag/v0.5.0
  - [x] Release plugins
  - [x] Release rules
    - [x] https://github.com/falcosecurity/rules/releases/tag/falco-rules-1.0.0
  - [x] Prebuilt drivers publish
    - [x] https://github.com/falcosecurity/test-infra/pull/1170
  - [x] Changelog
    - [x] https://github.com/falcosecurity/falco/pull/2619
- [x] **Release**
  - [x] Tag
  - [x] Github Release
- [x] **Website**
  - [x] https://github.com/falcosecurity/falco-website/pull/840
  - [x] https://github.com/falcosecurity/falco-website/pull/958
  - [x] https://github.com/falcosecurity/falco-website/pull/983
  - [x] https://github.com/falcosecurity/falco-website/pull/986
  - [x] https://github.com/falcosecurity/falco-website/pull/987
  - [x] Create 0.34 snapshot: https://github.com/falcosecurity/falco-website/tree/v0.34
    - [x] Protect snapshot branch: https://github.com/falcosecurity/test-infra/pull/1176
  - [x] 0.35 as latest: https://github.com/falcosecurity/falco-website/pull/992
- [x] **Announcements**
  - [x] mailing list 
  - [x] slack channel
- [x] **Post-Release**
  - [x] Update helm charts: https://github.com/falcosecurity/charts/pull/498
  - [x] Archive community call meeting notes: https://github.com/falcosecurity/community/pull/193
  - [x] publish plugins OCI artifacts

## Miscs

/milestone 0.35.0

/assign @fededp 

/kind documentation

**Comment by FedeDP** [comment]
Current plan:
* We found a couple of regressions in drivers 5.0.0; we will release an updated 5.0.1 patch release (https://github.com/falcosecurity/libs/milestone/17)
* We aim to tag 0.11 and 5.0.1 asap, tomorrow hopefully
* Drivers 5.0.1 will replace 5.0.0 on both Falco and test-infra (download.falco.org prebuilt artifacts)
* Falco 0.35.0 milestone should be completed during this week
* On wednesday 7th june we will tag Falco 0.35

I will update the issue body with the new informations.

**Comment by incertum** [comment]
@FedeDP unclear how we track updates to https://github.com/falcosecurity/falco/blob/master/userspace/engine/falco_engine_version.h#L19, I believe we added a few new fields after the last change?

**Comment by FedeDP** [comment]
Mmmh i think it is bumped just once per-release cycle. 
@jasondellaluce perhaps has more insights!

**Comment by jasondellaluce** [comment]
The engine version has been bumped already since the last released Falco version (0.34.1), so we should be good to go with version 17.

**Comment by FedeDP** [comment]
**BREAKING NEWS**: we will need a libs 0.11.1 tag: https://github.com/falcosecurity/libs/milestone/18

**Comment by FedeDP** [comment]
Update: libs 0.11.1 is going to be tagged soon.
Milestone 0.35.0 on Falco is completed (we only have this issue opened in it).
Rules have seen an RC tag: https://github.com/falcosecurity/rules/releases/tag/falco-rules-1.0.0-rc1
Plugins have been tagged.

**Comment by FedeDP** [comment]
Libs 0.11.1 tagged: https://github.com/falcosecurity/libs/releases/tag/0.11.1

**Comment by FedeDP** [comment]
The release workflow is currently running...https://github.com/falcosecurity/falco/actions/runs/5198352898

**Comment by FedeDP** [comment]
We found a small bug in the new release workflow; a PR is opened: https://github.com/falcosecurity/falco/pull/2621
The release was removed and we will re-publish it in a couple of hours.

**Comment by FedeDP** [comment]
We will also bump libs to 0.11.2: https://github.com/falcosecurity/libs/pull/1144

**Comment by FedeDP** [comment]
The PR with the fix and the libs bump is opened against the release branch: https://github.com/falcosecurity/falco/pull/2622

**Comment by FedeDP** [comment]
The new tag is live: https://github.com/falcosecurity/falco/releases/tag/0.35.0
Follow release workflow: https://github.com/falcosecurity/falco/actions/runs/5199822395

**Comment by FedeDP** [comment]
/close

Completed!
