### ISSUE TITLE
[Tracking] Falco v0.35.1

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/falco#2647]
## ETA: ~2023-06-29

As proposed during the community call of 2023-06-14, we plan to publish an hotfix release for Falco to include some relevant fixes merged after rolling out v0.35.0. I proposed myself as a release manager, and @loresuso confirmed his interest in shadowing.

### Status

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

- [x] **Falcoctl**
  - [x] https://github.com/falcosecurity/falcoctl/pull/292
  - [x] https://github.com/falcosecurity/falcoctl/pull/296
  - [x] https://github.com/falcosecurity/falcoctl/pull/298
  - [x] https://github.com/falcosecurity/falcoctl/pull/304 
  - [x] Release v0.5.1: https://github.com/falcosecurity/falcoctl/releases/tag/v0.5.1
- [x] **Falco Rules**
  - [x] https://github.com/falcosecurity/rules/pull/83
  - [x] Release v1.0.1: https://github.com/falcosecurity/rules/releases/tag/falco-rules-1.0.1
- [x] **Libs**
  - [x] https://github.com/falcosecurity/libs/pull/1148
  - [x] https://github.com/falcosecurity/libs/pull/1149
  - [x] https://github.com/falcosecurity/libs/pull/1160
  - [x] https://github.com/falcosecurity/libs/pull/1168
  - [x] https://github.com/falcosecurity/libs/pull/1173
  - [x] Sync [v0.11.x release branch](https://github.com/falcosecurity/libs/tree/release/0.11.x): https://github.com/falcosecurity/libs/pull/1177
  - [x] Release [v0.11.3](https://github.com/falcosecurity/libs/milestone/22): https://github.com/falcosecurity/libs/releases/tag/0.11.3
- [x] **Falco**
  - [x] https://github.com/falcosecurity/falco/pull/2437
  - [x] https://github.com/falcosecurity/falco/pull/2623
  - [x] https://github.com/falcosecurity/falco/pull/2627
  - [x] https://github.com/falcosecurity/falco/pull/2634
  - [x] https://github.com/falcosecurity/falco/pull/2635
  - [x] https://github.com/falcosecurity/falco/pull/2646
  - [x] https://github.com/falcosecurity/falco/pull/2648
  - [x] https://github.com/falcosecurity/falco/pull/2651
  - [x] https://github.com/falcosecurity/falco/pull/2652
  - [x] https://github.com/falcosecurity/falco/pull/2653
  - [x] https://github.com/falcosecurity/falco/pull/2661
  - [x] https://github.com/falcosecurity/falco/pull/2662
  - [x] Changelog: https://github.com/falcosecurity/falco/pull/2665
  - [x] Sync [v0.35.x release branch](https://github.com/falcosecurity/falco/tree/release/0.35.x): https://github.com/falcosecurity/falco/pull/2664
  - [x] https://github.com/falcosecurity/falco/pull/2642
  - [x] Sync [v0.35.x release branch](https://github.com/falcosecurity/falco/tree/release/0.35.x):  https://github.com/falcosecurity/falco/pull/2667
  - [x] Release [v0.35.1](https://github.com/falcosecurity/falco/milestone/33): https://github.com/falcosecurity/falco/releases/tag/0.35.1
- [x] **Website**
  - [x] Set v0.35.1 as latest: https://github.com/falcosecurity/falco-website/pull/1013
- [x] **Charts**
  - [x] Bump Falco to v0.35.1: https://github.com/falcosecurity/charts/pull/506
- [x] **Announcements**
  - [x] Website blog post: https://github.com/falcosecurity/falco-website/pull/1021
  - [x] Mailing list 
  - [x] Slack channel: https://kubernetes.slack.com/archives/CMWH3EH32/p1688057348892049

### Miscs

/milestone 0.35.1

/assign @jasondellaluce @loresuso 

/kind documentation
