### ISSUE TITLE
[TRACKING] Falco config changes to support rules maturity framework

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#2717]
**Feature**

Summarizing outcomes discussed during the core maintainers meeting on 2023-08-03.

Support better configurability of loading and enabling rules based on tags in support of rules maturity framework.

- [x] Expose `-t/-T` functionality over `falco.yaml`
- [ ] `enabled: false` shall override any rules loading mechanisms by tags filtering in order to be able to support loading rules from let's 3 tags for 3 maturity levels, but honoring that the adopter selectively disabled a couple of rules.
- [ ] On the flip side let's discuss behavior for `enabled: true` when a rules does not have the respective tag? It should not be loaded hence for positive scenarios rules tags selection shall take precedence
- [ ] add new / more unit tests for all of the above

**Additional context**

- See Falco rules maturity framework implementation Phase 4 https://github.com/falcosecurity/rules/issues/126
- Related to enhancements wrt to better override / merge configurability when redefining a rules YAML object https://github.com/falcosecurity/falco/pull/2671

**Comment by incertum** [comment]
@leogr and @LucaGuerra kindly asking to confirm all of the above. After that who would be the primary person working on it meaning the person who opens the PR?

**Comment by Andreagit97** [comment]
Yep, I like the -t, -T from the config. Moreover, once we have it in the config we could just keep it and calling from command line with the `-o` flag so we can also deprecate the other -t, -T flags.

I think the other 2 points are related to this: https://github.com/falcosecurity/falco/issues/2631

I think that we need to find a better way than using `-t, -T, -D`. we have too many flags for doing the same thing: manipulate which syscalls are enabled and which are not. Probably a new fresh config could allow us to cleanup all these flag and have a more intuitive behavior.

And yes I think we need to move it to 0.37 since here we don't have a design, but is something that we really need to address in the next release

**Comment by incertum** [comment]
Agree with you @leogr and @Andreagit97.

Especially agree that the command line args `-t, -T, -D` seem less useful. I think `falco.yaml` is more powerful from a DevOps perspective and as @Andreagit97 pointed out, any config in `falco.yaml` can be passed as command line arg as well.

re the multiple rules files and maturity level tagging: For some adopters it may be easier to consolidate them in one rules file and btw what about custom rules that get a maturity level assigned? Therefore we should fully support filtering and rules loading mechanisms that do not depend on the rule file.

re the `enabled: false` let's discuss more in the next dev cycle. We need to check what has precedence under what scenarios. I would vote for the following: When a rule defines `enabled: false` nothing should override this, even if you filter for tags that includes a disabled rule it should still not be loaded and enabled.

**Comment by LucaGuerra** [comment]
I think that's been addressed by https://github.com/falcosecurity/falco/issues/3174 . @incertum if confirmed could you please close this?

/milestone 0.39.0

**Comment by leogr** [comment]
This has been actually addressed within :point_down: 
/milestone 0.38.0
