### ISSUE TITLE
[Tracking] Falco 0.36.0 RC1

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#2750]
## Why?
Per the [Falco Roadmap Management Proposal](https://github.com/falcosecurity/falco/blob/master/proposals/20230511-roadmap-management.md#release-cycles-and-development-iterations) introduced by these release cycles, a Falco pre-release (or a viable development build) is expected during the [last week of each iteration](https://github.com/falcosecurity/falco/blob/master/proposals/20230511-roadmap-management.md#testing-and-quality-assurance-qa) to ensure adequate testing and QA. 

This issue is to track the release of Falco 0.36.0 RC1 for the above-stated purpose.

## ETA: ASAP early Sept.
Note: We planned to complete the "Stabilization" iteration in August, which should have resulted in a Falco pre-release. However, due to many maintainers and contributors being on vacation in the recent weeks, and as this is our first time implementing this new approach, we're running a bit behind schedule. This delay is still acceptable. Our realistic goal is to finalize Falco 0.36.0 RC1 around the 1st or the 2nd week of September.

## Status

```[tasklist]
## Blockers
- [ ] https://github.com/falcosecurity/rules/pull/149
- [x] rules 2.0.0 pre-release (including changes due to the newly introduced Rules Maturity Framework)
- [ ] [libs 0.13](https://github.com/falcosecurity/libs/milestones) release
- [ ] https://github.com/falcosecurity/falco/pull/2775
```

```[tasklist]
## Nice-To-Have
- [ ] Plugins (pre-)releases
- [x] falcoctl [v0.6.0 release](https://github.com/falcosecurity/falcoctl/milestone/6)
- [ ] https://github.com/falcosecurity/rules/issues/126
- [ ] https://github.com/falcosecurity/falco/pull/2718
```

**Comment by FedeDP** [comment]
PR to bump drivers to 6.0.0+driver and libs to 0.13.0-rc1: https://github.com/falcosecurity/falco/pull/2783

**Comment by FedeDP** [comment]
Note: we can manage multiple RCs; we might want a new RC with bumped plugins and 0.13.0 libs.
