### ISSUE TITLE
[Tracking] Falco 0.36.0

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/falco#2816]
# Falco 0.36.0 Release

Will keep this issue updated with the current status and progress.

## Date

Release date: 2023-09-26

## Release Steps

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

```[tasklist]
## Release Blocking PRs and issues
- [x] [Falco 0.36.0 milestone](https://github.com/falcosecurity/falco/milestone/30)
- [x] [Libs 0.13.1 milestone](https://github.com/falcosecurity/libs/milestone/27)
- [ ] https://github.com/falcosecurity/plugins/pull/356
- [x] Release libs 0.13.1
- [ ] https://github.com/falcosecurity/rules/issues/172
```

```[tasklist]
## External dependencies
- [x] falcoctl -> 0.6.1
- [x] libs -> 0.13.1
- [x] drivers -> 6.0.1+driver
- [x] rules -> 2.0.0
- [x] plugins -> https://github.com/falcosecurity/falco/pull/2820
- [x] charts
```

```[tasklist]
## Manual Testing Action Items
- [x] Running Falco on Kubernetes with the official Helm Charts
- [x] Running Falco from RPM and DEB artifacts
- [x] Running Falco in a container with the official images
- [x] Running/fuzzing Falco with multiple event sources active in parallel
- [x] Running/fuzzing Falco with variable syscall buffer dimension
- [x] Running Falco in all officially-supported architectures (x86_64, ARM64)
- [x] Running Falco with the supported drivers (kmod, modern eBPF, eBPF, gVisor, trace files)
- [x] Test Falco with event generator
- [x] Test that plugins are correctly loaded
- [x] Test memory and CPU usage (with Valgrind and other tools)
- [x] Test latest version of driver loader
- [x] Test that k8s metadata enrichment client works as expected
- [x] Test that all Falco CLI options work as expected
- [x] Check that Falco log messages are correct and consistent
- [x] Test that Falco ruleset loading and validation works as expected
```

## Action Items

- [x] **Pre-Release**
  - [x]  Milestone: https://github.com/falcosecurity/falco/milestone/30
  - [x] Code freeze in falcosecurity/falco
  - [x] Open release branch in Falco and protect it
  - [x] See `External dependencies` task lists
  - [x] Prebuilt drivers publish
  - [x] Code thaw in falcosecurity/falco
  - [x] Changelog
- [x] **Release**
  - [x] Github Release in the Falco repo
- [x] **Website**
  - [x] Create new snapshot
    - [x] Protect snapshot branch
  - [ ] Merge all necessary PRs
- [x] **Helm**
  - [x] Release a new helm chart version
  - [x] Update helm chart documentation
  - [x] Add instructions to the Helm chart readme about how to switch images if necessary https://github.com/falcosecurity/charts/pull/538
- [x] **Announcements**
  - [x] mailing list 
  - [x] blog post
  - [x] slack channel
- [x] **Post-Release**
  - [x] Update supported fields and syscall documentation https://github.com/falcosecurity/falco-website/pull/1164
  - [x] Archive community call meeting notes https://github.com/falcosecurity/community/pull/198

## Miscs

/milestone 0.36.0

/assign @LucaGuerra

/kind documentation

# PRs that should be cherry-picked into the release branch

- [x] https://github.com/falcosecurity/falco/pull/2810
- [x] https://github.com/falcosecurity/falco/pull/2813
- [x] https://github.com/falcosecurity/falco/pull/2814
- [x] https://github.com/falcosecurity/falco/pull/2815
- [x] https://github.com/falcosecurity/falco/pull/2820
- [x] https://github.com/falcosecurity/falco/pull/2819
- [x] https://github.com/falcosecurity/falco/pull/2809
- [x] https://github.com/falcosecurity/falco/pull/2823
- [x] https://github.com/falcosecurity/falco/pull/2822
- [x] https://github.com/falcosecurity/falco/pull/2824

Synced with: https://github.com/falcosecurity/falco/pull/2825

---

- [x] https://github.com/falcosecurity/falco/pull/2834
- [x] https://github.com/falcosecurity/falco/pull/2812
- [x] https://github.com/falcosecurity/falco/pull/2828
- [x] https://github.com/falcosecurity/falco/pull/2829
- [x] https://github.com/falcosecurity/falco/pull/2826
- [x] https://github.com/falcosecurity/falco/pull/2830
- [x] https://github.com/falcosecurity/falco/pull/2831
- [x] https://github.com/falcosecurity/falco/pull/2833

Synced with: https://github.com/falcosecurity/falco/pull/2835

---

**Comment by LucaGuerra** [comment]
Moving the date to tomorrow to allow for a tiny bit of extra testing.
