### ISSUE TITLE
[Tracking] Falco 0.36.1

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/falco#2861]
# Falco 0.36.1 Release

Will keep this issue updated with the current status and progress.

## Date

Release date: 2023-10-16

## Release Steps

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

```[tasklist]
## Release Blocking PRs and issues
- [x] [Falco 0.36.1 milestone](https://github.com/falcosecurity/falco/milestone/35)
- [x] [Libs 0.13.2 milestone](https://github.com/falcosecurity/libs/milestone/29)
```

```[tasklist]
## External dependencies
- [x] falcoctl -> Not needed
- [x] libs -> https://github.com/falcosecurity/libs/releases/tag/0.13.2
- [x] drivers -> Not needed
- [x] rules -> Not needed
- [x] plugins -> Not needed
- [x] charts-> https://github.com/falcosecurity/charts/releases/tag/falco-3.8.0
```

```[tasklist]
## Manual Testing Action Items
- [x] Running Falco on Kubernetes with the official Helm Charts
- [x] Running Falco from RPM and DEB artifacts
- [x] Running Falco in a container with the official images
- [x] Running/fuzzing Falco with multiple event sources active in parallel
- [x] Running/fuzzing Falco with variable syscall buffer dimension
- [x] Running Falco in all officially-supported architectures (x86_64, ARM64)
- [x] Running Falco with the supported drivers (kmod, modern eBPF, eBPF, gVisor, trace files)
- [x] Test Falco with event generator
- [x] Test that plugins are correctly loaded
- [x] Test memory and CPU usage (with Valgrind and other tools)
- [x] Test latest version of driver loader
- [x] Test that k8s metadata enrichment client works as expected
- [x] Test that all Falco CLI options work as expected
- [x] Check that Falco log messages are correct and consistent
- [x] Test that Falco ruleset loading and validation works as expected
```

## Action Items

- [x] **Pre-Release**
  - [x]  Milestone: https://github.com/falcosecurity/falco/milestone/30
  - [x] Code freeze in falcosecurity/falco
  - [x] Open release branch in Falco and protect it
  - [x] See `External dependencies` task lists
  - [x] Prebuilt drivers publish
  - [x] Code thaw in falcosecurity/falco
- [x] **Release**
  - [x] Github Release in the Falco repo
- [x] **Website**
  - [x] Create new snapshot
    - [x] Protect snapshot branch
  - [x] Merge all necessary PRs
- [x] **Helm**
  - [x] Release a new helm chart version
  - [x] Update helm chart documentation
  - [x] Add instructions to the Helm chart readme about how to switch images if necessary
- [x] **Announcements**
  - [x] mailing list 
  - [x] blog post
  - [x] slack channel
- [x] **Post-Release**
  - [x] Update supported fields and syscall documentation
  - [x] Archive community call meeting notes
  - [x] Changelog

## Miscs

/milestone 0.36.1

/assign @Andreagit97

/kind documentation

# PRs that should be cherry-picked into the release branch

- [x] https://github.com/falcosecurity/falco/pull/2863
- [x] https://github.com/falcosecurity/falco/pull/2851

Synced with: https://github.com/falcosecurity/falco/pull/2868 (this PR includes also the libs bump to 0.13.2-rc1)

---

**Comment by Andreagit97** [comment]
Falco 0.36.1 is out! Thank you all!
