### ISSUE TITLE
[UMBRELLA] Errors at Falco start-up related to Falco's kernel driver {kmod, bpf, modern_bpf}

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#2873]
Umbrella issue for community members to post start-up error messages related to Falco's kernel driver {kmod, bpf, modern_bpf}.

```[tasklist]
### Tasks
- [ ] https://github.com/falcosecurity/falco/issues/2874
- [ ] https://github.com/falcosecurity/falco/issues/2792
- [ ] https://github.com/falcosecurity/falco/issues/2884
- [ ] https://github.com/falcosecurity/falco/issues/2964
- [ ] https://github.com/falcosecurity/falco/issues/2989
- [ ] https://github.com/falcosecurity/falco/issues/2982
```

**Comment by incertum** [comment]
@EdikAndriasyan reposting your initial question:

> Hey, I am deploying Falco in GKE cluster(v1.24) with helm chart(3.7.1). Using ebpf module and deploying Falco as DaemonSet. I am getting this error in Falco logs.
> 
> `-- BEGIN PROG LOAD LOG --
processed 43798 insns (limit 1000000) max_states_per_insn 1 total_states 4061 peak_states 4061 mark_read 1921
> 
> -- END PROG LOAD LOG --
> Mon Oct 16 09:06:37 2023: An error occurred in an event source, forcing termination...
> Mon Oct 16 09:06:37 2023: Closing event source 'syscall'
> Events detected: 0
> Rule counts by severity:
> Triggered rules by rule name:
> Error: libscap: bpf_load_program() event=raw_tracepoint/filler/sys_procexit_e: Operation not permitted`

**Comment by incertum** [comment]
@EdikAndriasyan mind posting the kernelrelease? Thank you!
