### ISSUE TITLE
[Tracking] Falco 0.36.2

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/falco#2885]
# Falco 0.36.2 Release

Will keep this issue updated with the current status and progress.

## Date

Release date: 2023-13-03

## Release Steps

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

```[tasklist]
## Release Blocking PRs and issues
- [ ] [Falco 0.36.2 milestone](https://github.com/falcosecurity/falco/milestone/36)
- [ ] [Libs 0.13.3 milestone](https://github.com/falcosecurity/libs/milestone/30)
```

```[tasklist]
## External dependencies
- [x] falcoctl -> Not needed
- [ ] libs
- [x] drivers -> Not needed
- [x] rules -> Not needed
- [x] plugins -> Not needed
- [x] charts-> Not needed
```

## Action Items

- [x] **Pre-Release**
  - [ ]  Milestone
  - [x] Code freeze in falcosecurity/falco
  - [x] Open release branch in Falco and protect it
  - [x] See `External dependencies` task lists
  - [x] Prebuilt drivers publish
  - [x] Code thaw in falcosecurity/falco
- [ ] **Release**
  - [ ] Github Release in the Falco repo
- [ ] **Website**
  - [ ] Create new snapshot
    - [ ] Protect snapshot branch
  - [ ] Merge all necessary PRs
- [ ] **Announcements**
  - [ ] mailing list 
  - [ ] blog post
  - [ ] slack channel
- [ ] **Post-Release**
  - [ ] Update supported fields and syscall documentation
  - [ ] Archive community call meeting notes
  - [ ] Changelog

## Miscs

/milestone 0.36.2

/assign @FedeDP

/kind documentation

---

**Comment by FedeDP** [comment]
A new bug in libs was discovered and promptly fixed: https://github.com/falcosecurity/libs/pull/1449
A new tag 0.13.4 was made!

**Comment by FedeDP** [comment]
Falco 0.36.2 tag is live; pipeline did start: https://github.com/falcosecurity/falco/actions/runs/6665609097

**Comment by FedeDP** [comment]
Release is out, everything done.
/close
