### ISSUE TITLE
[Tracking] Falco 0.37.0

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/falco#3003]
# Falco 0.37.0 Release

Will keep this issue updated with the current status and progress.

## Date

Target release date: 2024-01-30

## Release Steps

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

```[tasklist]
## External dependencies
- [x] falcoctl -> 0.7.1
- [x] libs -> 0.14.2
- [x] drivers -> 7.0.0+driver
- [x] rules -> 3.0.0
- [x] plugins bump
```

```[tasklist]
## Manual Testing Action Items
- [x] Running Falco on Kubernetes with the official Helm Charts
- [x] Running Falco from RPM and DEB artifacts
- [x] Running Falco in a container with the official images
- [x] Running/fuzzing Falco with multiple event sources active in parallel
- [x] Running/fuzzing Falco with variable syscall buffer dimension
- [x] Running Falco in all officially-supported architectures (x86_64, ARM64)
- [x] Running Falco with the supported drivers (kmod, modern eBPF, eBPF, gVisor, trace files)
- [x] Test Falco with event generator
- [x] Test that plugins are correctly loaded
- [x] Test memory and CPU usage (with Valgrind and other tools)
- [x] Test latest version of driver loader
- [x] Test that `k8smeta` plugin works as expected
- [x] Test that all Falco CLI options work as expected
- [x] Check that Falco log messages are correct and consistent
- [x] Test that Falco ruleset loading and validation works as expected
- [x] Test Falco with Gvisor
```

## Action Items

- [x] **Pre-Release**
  - [x]  Milestone
  - [x] Code freeze in falcosecurity/falco
  - [x] Open release branch in Falco and protect it
  - [x] See `External dependencies` task lists
  - [x] Prebuilt drivers publish
  - [x] Code thaw in falcosecurity/falco
  - [x] Changelog on the release branch
  - [x] cherry-pick the changelog on master
- [x] **Release**
  - [x] Github Release in the Falco repo
- [x] **Website**
  - [x] Create new snapshot
    - [x] Protect snapshot branch
  - [x] Merge the release blog post
  - [x] Merge all necessary documentation PRs
- [x] **Helm**
  - [x] Release a new helm chart version
  - [x] Update helm chart documentation
  - [x] Add instructions to the Helm chart readme about how to switch images if necessary
- [x] **Announcements**
  - [x] mailing list 
  - [x] blog post
  - [x] slack channel
- [x] **Post-Release**
  - [x] Archive community call meeting notes
  - [x] Close the resolved issues after the tag and move the unresolved ones under a new milestone
  - [x] Update supported fields and syscall documentation

## Miscs

/milestone 0.37.0

/assign @Andreagit97 

/kind documentation

# PRs that should be cherry-picked into the release branch

- https://github.com/falcosecurity/falco/pull/3030
- https://github.com/falcosecurity/falco/pull/3028

Synced with: https://github.com/falcosecurity/falco/pull/3031

---

- https://github.com/falcosecurity/falco/pull/3032
- https://github.com/falcosecurity/falco/pull/3033
- https://github.com/falcosecurity/falco/pull/3015
- https://github.com/falcosecurity/falco/pull/3034

Synced with: https://github.com/falcosecurity/falco/pull/3035

---

- https://github.com/falcosecurity/falco/pull/3036 directly pushed on the release branch
- https://github.com/falcosecurity/falco/pull/3040 directly pushed on the release branch
---

**Comment by Andreagit97** [comment]
Falco 0.37.0-rc1 is out https://github.com/falcosecurity/falco/releases/tag/0.37.0-rc1!
Please help us test it if you have time!

**Comment by Andreagit97** [comment]
Falco 0.37.0-rc2 is out https://github.com/falcosecurity/falco/releases/tag/0.37.0-rc2!
Please help us test it if you have time!

**Comment by Andreagit97** [comment]
Falco 0.37.0-rc3 is out https://github.com/falcosecurity/falco/releases/tag/0.37.0-rc3!
Please help us test it if you have time!

**Comment by Andreagit97** [comment]
Falco 0.37.0 is finally out https://github.com/falcosecurity/falco/releases/tag/0.37.0! :rocket:
