### ISSUE TITLE
[maintenance] cpp cleanup

### ISSUE THREAD

**Issue by sgaist** [falcosecurity/falco#3052]
**Motivation**

I am opening this ticket as a followup to a discussion I am having with @incertum.

While working on  #2890 and #2974, I saw potential to improve some things in the code base.

I am not currently talking about low level refactoring of core functionalities but improvement of the code itself to make the life of new and old falco developers easier.

What this ticket is **not**: a suggestion for a revolution.

**Proposition**

There are several aspects that I would like to help improve:

- code being more idiomatic C++ (for example, declare and use a variable in one line)
- const correctness
- override correctness
- avoid shadowing (variables, parameters or functions)
- ensure proper initialization

As a mean to that end, I have run cppcheck on the code base and it has found things in the above list and some more such as suggestions around using stl algorithms in place of loops in some places and the use of some deprecated APIs.

What I think would be nice is to devise a plan so that the various cleanup do not interfere too much with the current pull requests.

One possible way to go forward:

- Make PRs in engine and app separately even if the topics are the same
- Create PRs per type of cleanup (don't mix const correctness with override correctness)
- Decide if there are some things that should not change (for example keep loops as is rather than stl algorithms)
- Once done add a cppcheck action to the pipeline to ensure the code keeps its quality

Some questions around the organisation of that:
- Should there be one ticket per type of cleanup to track the work ?
- Use the [task list](https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/about-tasklists) feature of GitHub ?
- Should the cleanup happen in a separate branch that will be rebased regularly until all the cleanups are done ?

Further suggestions are welcome

Note: I know some changes might rather be style related when thinking about idiomatic C++ so another question would be should they wait for https://github.com/falcosecurity/libs/issues/381 to be done ?

### Tasks
- [x] https://github.com/falcosecurity/falco/issues/3063
- [x] https://github.com/falcosecurity/falco/issues/3068
- [ ] https://github.com/falcosecurity/falco/issues/3082
- [ ] https://github.com/falcosecurity/falco/issues/3073
- [ ] https://github.com/falcosecurity/falco/issues/3122
- [ ] Refactor variable initialization on use
- [ ] Transform loop to std::algorithm
- [ ] https://github.com/falcosecurity/falco/issues/3084
- [ ] https://github.com/falcosecurity/falco/issues/3096

**Comment by incertum** [comment]
CC @falcosecurity/falco-maintainers - we will take a look soon! Thanks a bunch 🚀 !

**Comment by leogr** [comment]
Hey @sgaist 

Thank you for your proposal! Here's my feedback.

> * Create PRs per type of cleanup (don't mix const correctness with override correctness)

I guess this :point_up:  would let us evaluate cleanups case by case and then :point_down: 

> Decide if there are some things that should not change (for example, keep loops as is rather than stl algorithms)

(sometimes, to decide if a change worth to be introducing or not, just a simple `wip:`/incomplete PR is enough)

> Use the [task list](https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/about-tasklists) feature of GitHub ?
Yes, please :pray: 

> Should the cleanup happen in a separate branch that will be rebased regularly until all the cleanups are done ?

I believe the easiest way to move this forward is to make a PR per cleanup sequentially (each PR is a separate branch).

> Note: I know some changes might rather be style related when thinking about idiomatic C++ so another question would be should they wait for https://github.com/falcosecurity/libs/issues/381 to be done ?

This is the big question :) 
That initiative has been blocked due to a lack of capacity. Before proceeding, we should at least agree on the overall style. 

Let's see what other maintainers think about this.

**Comment by incertum** [comment]
> we should at least agree on the overall style.

I would appreciate this as depending on the PR I also experienced varying style feedback 🙃 A more realistic timeline would perhaps be June/July 2024 (post Falco 0.38.0)?

**Comment by Andreagit97** [comment]
> I believe the easiest way to move this forward is to make a PR per cleanup sequentially (each PR is a separate branch).

I agree to proceed in this way! 

> That initiative has been blocked due to a lack of capacity. Before proceeding, we should at least agree on the overall style.

Yeah at a certain point, we need to revamp this discussion!

**Comment by LucaGuerra** [comment]
Thank you for the suggestions! I am in favor of cleaning up the code, especially because lately we have been working to remove some potential sources of segfaults, undefined behavior and so on. I have some suggestions about it:
* You mentioned you used CppCheck to discover these issues and we also run CppCheck in our workflow but perhaps it needs a little maintenance so that it warns on the right things. Could you please edit our static analysis jobs to suggest some checks to add to our CI? If they are not enforced or at least mentioned your work will sadly be lost in a short amount of time.
* Out of all the cleanups, using algorithm is the one that sounds a bit more cumbersome because we have a lot of loops; personally I would keep that one out unless there is a very valid reason to do so, and that would require a bit more agreement
* We are doing something similar for dynamic analysis as well (see https://github.com/falcosecurity/falco/issues/2930 and https://github.com/falcosecurity/falco/pull/3066)

**Comment by sgaist** [comment]
* From the looks of it, the `static-analysis.cmake` contains a more aggressive configuration for cppcheck than the one I have been using. Currently my command is `cppcheck -i ./build --enable=warning,style,performance,portability 2>err.txt`. We might be using a different version of cppcheck though. I am running it from my macOS command line while building falco in a Linux docker container (It might be a bit of an exotic setup, I should rather spin a virtual machine to be working 100% in Linux).
I am wondering whether there should be a reference platform for development like for example Debian 12, Ubuntu 22.04, etc. document. That way it might help new contributors be on the same page as the core developers.
* I agree with the algorithm part, it does not always make sense to move over to them just for the sake of doing it. A careful analysis is needed.
* Adding sanitizers is a very good idea. I am wondering whether doing some fuzzing would also be of interest.

**Comment by FedeDP** [comment]
@sgaist still relevant?

**Comment by sgaist** [comment]
From a quick check, yes it is.

I have to take some time to finalize this.

**Comment by leogr** [comment]
@sgaist anything still missing here? 🤔

**Comment by sgaist** [comment]
@leogr sorry, I got sidetracked on this task.

I'll check that in the coming days and update the status of this ticket.

**Comment by sgaist** [comment]
@leogr It took me a bit longer but I just run a check and there are still some stuff around that can be improved. I'll try to tackle that in the very near future.
