### ISSUE TITLE
[Tracking 0.37.1] Falco 0.37.1

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/falco#3061]
# Falco 0.37.1 Release

Will keep this issue updated with the current status and progress.

## Date

Target release date:

## Release Steps

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

```[tasklist]
## External dependencies
- [ ] falcoctl ->
- [ ] libs ->
- [ ] drivers -> 
- [ ] rules ->
- [ ] plugins bump
```

```[tasklist]
## Manual Testing Action Items
- [x] Running Falco on Kubernetes with the official Helm Charts
- [x] Running Falco from RPM and DEB artifacts
- [x] Running Falco in a container with the official images
- [x] Running/fuzzing Falco with multiple event sources active in parallel
- [x] Running/fuzzing Falco with variable syscall buffer dimension
- [x] Running Falco in all officially-supported architectures (x86_64, ARM64)
- [x] Running Falco with the supported drivers (kmod, modern eBPF, eBPF, gVisor, trace files)
- [x] Test Falco with event generator
- [x] Test that plugins are correctly loaded
- [x] Test memory and CPU usage (with Valgrind and other tools)
- [x] Test latest version of driver loader
- [x] Test that `k8smeta` plugin works as expected
- [x] Test that all Falco CLI options work as expected
- [x] Check that Falco log messages are correct and consistent
- [x] Test that Falco ruleset loading and validation works as expected
- [x] Test Falco with Gvisor
```

## Action Items

- [x] **Pre-Release**
  - [x]  Milestone
  - [x] Code freeze in falcosecurity/falco
  - [x] Open release branch in Falco and protect it
  - [x] See `External dependencies` task lists
  - [x] Prebuilt drivers publish
  - [x] Code thaw in falcosecurity/falco
  - [x] Changelog on the release branch
  - [x] cherry-pick the changelog on master
- [x] **Release**
  - [x] Github Release in the Falco repo
- [x] **Website**
  - [x] Create new snapshot
    - [x] Protect snapshot branch
  - [x] Merge the release blog post
  - [x] Merge all necessary documentation PRs
- [x] **Helm**
  - [x] Release a new helm chart version
  - [x] Update helm chart documentation
  - [x] Add instructions to the Helm chart readme about how to switch images if necessary
- [x] **Announcements**
  - [x] mailing list 
  - [x] blog post
  - [x] slack channel
- [x] **Post-Release**
  - [x] Archive community call meeting notes
  - [x] Close the resolved issues after the tag and move the unresolved ones under a new milestone
  - [x] Update supported fields and syscall documentation
  - [x] add Falco version to the rules CI: https://github.com/falcosecurity/rules/pull/221

## Miscs

/milestone 0.37.1

/kind documentation

# PRs that should be cherry-picked into the release branch

-

Synced with: 

---

**Breaking change**
- supporting dynamic linking for libelf we introduce breaking changes
  - Falco `tar.gz` needs libelf installed on the system, since it is no longer shipped statically inside the Falco binary
  - Falco musl packages won't be shipped anymore

**Comment by FedeDP** [comment]
Tag created: https://github.com/falcosecurity/falco/releases/tag/0.37.1-rc1
Waiting on CI: https://github.com/falcosecurity/falco/actions/runs/7872714349

It spots libs 0.14.3 (https://github.com/falcosecurity/libs/releases/tag/0.14.3) and falcoctl v0.7.2 (https://github.com/falcosecurity/falcoctl/releases/tag/v0.7.2).

**Comment by FedeDP** [comment]
4 PRs to go:
* https://github.com/falcosecurity/charts/pull/622
* https://github.com/falcosecurity/rules/pull/228
* https://github.com/falcosecurity/falco-website/pull/1270
* https://github.com/falcosecurity/community/pull/205
