### ISSUE TITLE
WIP: [TRACKING] Falco 1.0 items

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#3148]
**Motivation**

We recently published the high-level [roadmap for Falco 1.0](https://falco.org/docs/roadmap/). Although we don't have a target date yet, we already have some items around, planned for 1.0, that directly affect the Falco application. This issue only aims to track these items/issues.

A dedicated GitHub issue is available only for [deprecations we may want to introduce in Falco 1.0](https://github.com/falcosecurity/falco/issues/3038)

```[tasklist]
### Falco 1.0.0 items
- [ ] https://github.com/falcosecurity/falco/issues/3038
- [ ] https://github.com/falcosecurity/rules/issues/211
- [ ] https://github.com/falcosecurity/falco/issues/3255
- [ ] https://github.com/falcosecurity/falco/issues/3254
- [ ] https://github.com/falcosecurity/falco/issues/3165
- [ ] https://github.com/falcosecurity/falco/issues/3194
- [ ] https://github.com/falcosecurity/falco/issues/3049
- [ ] https://github.com/falcosecurity/falco/issues/1332
- [ ] https://github.com/falcosecurity/libs/issues/2057
- [ ] https://github.com/falcosecurity/falco/issues/1859
```
