### ISSUE TITLE
[Tracking] Falco 0.38.0 Release

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#3197]
# Falco 0.38.0 Release

Will keep this issue updated with the current status and progress.

## Date

Target release date: May 30th 2024

## Release Steps

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

```[tasklist]
## External dependencies
- [x] falcoctl -> [0.8.0](https://github.com/falcosecurity/falcoctl/releases/tag/v0.8.0)
- [x] libs -> [0.17.0](https://github.com/falcosecurity/libs/releases/tag/0.17.0)
- [x] drivers -> [7.2.0+driver](https://github.com/falcosecurity/libs/releases/tag/7.2.0%2Bdriver)
- [x] rules -> [3.1.0](https://github.com/falcosecurity/rules/releases/tag/falco-rules-3.1.0)
- [x] plugins bump
```

```[tasklist]
## Manual Testing Action Items
- [x] Running Falco on Kubernetes with the official Helm Charts
- [x] Running Falco from RPM and DEB artifacts
- [x] Running Falco in a container with the official images
- [x] Running/fuzzing Falco with multiple event sources active in parallel
- [x] Running/fuzzing Falco with variable syscall buffer dimension
- [x] Running Falco in all officially-supported architectures (x86_64, ARM64)
- [x] Running Falco with the supported drivers (kmod, modern eBPF, eBPF, gVisor, trace files)
- [x] Test Falco with event generator
- [x] Test that plugins are correctly loaded
- [x] Test memory and CPU usage (with Valgrind and other tools)
- [x] Test latest version of driver loader
- [x] Test that `k8smeta` plugin works as expected
- [x] Test that all Falco CLI options work as expected
- [x] Check that Falco log messages are correct and consistent
- [x] Test that Falco ruleset loading and validation works as expected
- [x] Test Falco with Gvisor
```

## Action Items

- [x] **Pre-Release**
  - [x]  Milestone
  - [x] Code freeze in falcosecurity/falco
  - [x] Open release branch in Falco and protect it
  - [x] See `External dependencies` task lists
  - [x] Prebuilt drivers publish
  - [x] Code thaw in falcosecurity/falco
  - [x] Changelog on the release branch
  - [x] cherry-pick the changelog on master
- [x] **Release**
  - [x] Github Release in the Falco repo
- [x] **Website**
  - [x] Create new snapshot
    - [x] Protect snapshot branch
  - [x] Merge the release blog post
  - [x] Merge all necessary documentation PRs
- [x] **Helm**
  - [x] Release a new helm chart version
  - [x] Update helm chart documentation
- [x] **Announcements**
  - [x] mailing list 
  - [x] blog post
  - [x] slack channel
- [x] **Post-Release**
  - [x] Archive community call meeting notes
  - [x] Close the resolved issues after the tag and move the unresolved ones under a new milestone
  - [x] Update supported fields and syscall documentation
  - [x] add Falco version to the rules CI:

## Miscs

/milestone 0.38.0

/assign LucaGuerra

/kind documentation
