### ISSUE TITLE
[UMBRELLA] Streamlining `falco.yaml` structure

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#3254]
**Motivation**

This issue aims to collect all issues related to the Falco config streamlining initiative, as per the [Falco 1.0.0 roadmap](https://falco.org/docs/roadmap/#road-to-falco-1-0-0)

**Feature**

```[tasklist]
### Tasks
- [ ] [comment about container engine config](https://github.com/falcosecurity/falco/issues/3243#issuecomment-2180136262)
- [ ] https://github.com/falcosecurity/falco/issues/3235
- [ ] https://github.com/falcosecurity/falco/issues/3086
```

**Comment by leogr** [comment]
We can consider this as done. If anything further comes up, we will open a separate issue.

/close
