### ISSUE TITLE
[Tracking] Falco 0.38.2

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#3289]
# Falco 0.38.2 Release

Will keep this issue updated with the current status and progress.

This release contains several fixes developed in the last ~2 months, most importantly:
* Fixing a crash when using transformers with an empty string parameter
* FIxing some network comparison in rules not behaving correctly
* Fixing experimental Prometheus metrics names
* Fixing a kernel module crash in some kernel versions in RHEL9

## Date

Target release date: August 19th, 2024

## Release blocking PRs

```[tasklist]
### Release Blocking PRs
- [ ] https://github.com/falcosecurity/libs/pull/1992
```

## Release Steps

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

```[tasklist]
## External dependencies
- [x] falcoctl -> v0.9.0 https://github.com/falcosecurity/falcoctl/releases/tag/v0.9.0
- [x] libs -> 0.17.3 https://github.com/falcosecurity/falco/pull/3294
- [x] drivers ->  7.2.1: https://github.com/falcosecurity/libs/releases/tag/7.2.1%2Bdriver
- [x] rules -> NO CHANGES
- [x] plugins bump -> NO CHANGES
```
## Action Items

- [x] **Pre-Release**
  - [x]  Milestone
  - [x] Code freeze in falcosecurity/falco
  - [x] Open release branch in Falco and protect it
  - [x] See `External dependencies` task lists
  - [x] Prebuilt drivers publish
  - [x] Code thaw in falcosecurity/falco
  - [x] Changelog on the release branch https://github.com/falcosecurity/falco/pull/3293
  - [x] cherry-pick the changelog on master https://github.com/falcosecurity/falco/pull/3300
- [x] **Release**
  - [x] Github Release in the Falco repo
- [x] **Website**
  - [x] Create new snapshot
    - [x] Protect snapshot branch
  - [x] Merge the release blog post https://github.com/falcosecurity/falco-website/pull/1350
  - [x] Merge all necessary documentation PRs https://github.com/falcosecurity/falco-website/pull/1349
- [x] **Helm**
  - [x] Release a new helm chart version https://github.com/falcosecurity/charts/pull/726
  - [x] Update helm chart documentation
- [x] **Announcements**
  - [x] mailing list 
  - [x] blog post
  - [x] slack channel
- [x] **Post-Release**
  - [x] Close the resolved issues after the tag and move the unresolved ones under a new milestone
  - [x] Update supported fields and syscall documentation
  - [x] add Falco version to the rules CI https://github.com/falcosecurity/rules/pull/262

## Miscs

/milestone 0.38.2

/kind documentation

# PRs that should be cherry-picked into the release branch

-

Synced with: 

---

**Comment by LucaGuerra** [comment]
This release is now complete.
