### ISSUE TITLE
[UMBRELLA] Missing syscalls

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#676]
**What would you like to be added**:

Missing syscalls:

- [x] `execveat`
- [x] `copy_file_range`
- [x] `renameat2` (https://github.com/draios/sysdig/issues/1603)
- [x] `open_by_handle_at`
- [x] `userfaultfd` (https://github.com/falcosecurity/libs/pull/50)

**Why is this needed**:

This issue serves now as an umbrella issue to track the syscall the [kernel module and/or eBPF driver](https://github.com/falcosecurity/libs/tree/master/driver) are missing.

**Comment by leodido** [comment]
Since we also have evidence of other missing syscall we could use this issue to track all of them.

Otherwise we can close this. When we'll have the `execveat` in the kernel module we'll reopen it.

**Comment by fntlnz** [comment]
This also needs rules updates.

**Comment by jalseth** [comment]
/assign

Targeting the 1.0.0 release, I'm basing the missing syscalls off of the latest stable kernel in GKE, which is 4.19. I will focus on the ones that obviously have security implications first, that way if we want to cut a release 1.0.0 without monitoring of some of the syscalls that aren't security related, we can.

```
copy_file_range
execveat
fadvise64_64
fanotify_mark
ftruncate64
get_mempolicy
gethostname
io_pgetevents
ioperm
kcmp
kexec_file_load
lookup_dcookie
mbind
membarrier
memfd_create
migrate_pages
mlock2
move_pages
name_to_handle_at
ni_syscall
open_by_handle_at
pciconfig_iobase
pciconfig_read
pciconfig_write
pkey_alloc
pkey_free
pkey_mprotect
preadv2
pwritev2
readahead
renameat2
rseq
sched_getattr
sched_setattr
semtimedop
set_mempolicy
sigaction
sigsuspend
spu_create
spu_run
statx
sync_file_range
sync_file_range2
truncate64
userfaultfd
```

**Comment by leodido** [comment]
/keep
L.

**Comment by leogr** [comment]
I have found another missing syscall:
- `openat2` (might be needed by [several macros](https://github.com/falcosecurity/falco/blob/3bfd94fefd1cf7bb3a5c01cb38c27d8bb3402ea6/rules/falco_rules.yaml#L36) and [this rule](https://github.com/falcosecurity/falco/blob/master/rules/falco_rules.yaml#L2228))

Also added a [todo here](https://github.com/falcosecurity/falco/pull/1250/files#diff-6acd8aa2e534d1ed83e275bf658d936bR58) for `renameat2`, more context :point_right: https://github.com/falcosecurity/falco/pull/1250

**Comment by FedeDP** [comment]
I think we can close this one and eventually open a new issue when new syscalls get requested. We are pretty solid at the moment IMO :)
